/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/lafilogo.glb -t 
*/

import * as THREE from 'three'
import React, { useLayoutEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    tmp41egfasqobj: THREE.Mesh
  }
  materials: {
    pbr_material: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/LPECSITE/lafilogo-transformed.glb') as GLTFResult

  // Aperfeiçoamento da cor para forçar o brilho laranja
  useLayoutEffect(() => {
    if (materials.pbr_material) {
      materials.pbr_material.color.set('#ffa64d'); // Cor mais clara para refletir melhor
      materials.pbr_material.metalness = 0.7; // Mais metálico
      materials.pbr_material.roughness = 0.3; // Mais polido
      materials.pbr_material.emissive = new THREE.Color('#ff6d00');
      materials.pbr_material.emissiveIntensity = 0.25; // O próprio objeto emite cor laranja subtilmente
      materials.pbr_material.needsUpdate = true;
    }
  }, [materials]);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tmp41egfasqobj.geometry} material={materials.pbr_material} position={[-0.003, -0.01, 0.001]} scale={0.65} />
    </group>
  )
}

useGLTF.preload('/LPECSITE/lafilogo-transformed.glb')
